# /etc/skel/.bash_profile
# this file run by login shells

if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

cd ~/

# custom here
export PATH=/home/me/.local/bin:/home/me/.cargo/bin:$PATH # rust path
# force gpu stuff
export VDPAU_DRIVER=radeonsi
export LIBVA_DRIVER_NAME=radeonsi
# ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
# qt theme
export QT_QPA_PLATFORMTHEME=qt6ct
